// .vitepress/theme/components/ConfigTable.vue
<script setup lang="ts">
interface ConfigRow {
  variable: string;
  description: string;
  defaultValue: string;
}

defineProps<{
  rows: ConfigRow[];
}>();
</script>

<template>
  <div class="config-table">
    <table>
      <thead>
        <tr>
          <th>Variable</th>
          <th>Description</th>
          <th>Default</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, index) in rows" :key="index">
          <td>
            <code>{{ row.variable }}</code>
          </td>
          <td>{{ row.description }}</td>
          <td>
            <code>{{ row.defaultValue }}</code>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
.config-table {
  margin: 1.5rem 0;
  overflow-x: auto;
}

.config-table table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9rem;
  display: table;
}

.config-table th,
.config-table td {
  border: 1px solid var(--vp-c-divider);
  padding: 0.6rem 0.8rem;
  text-align: left;
  vertical-align: top;
}

.config-table th {
  background-color: var(--vp-c-bg-soft);
  font-weight: 600;
  color: var(--vp-c-text-1);
}

.config-table tbody tr:nth-child(even) {
  background-color: var(--vp-c-bg-soft);
}

.config-table td code {
  font-family: var(--vp-font-family-mono);
  font-size: 0.85em;
  background-color: transparent;
  padding: 0;
  color: var(--vp-c-brand-1);
}

.config-table td:nth-child(3) code {
  color: var(--vp-c-text-2);
}
</style>

// components/ConfigTable.tsx
'use client';

import React from 'react';

interface TableRow {
  variable: string;
  description: string;
  defaultValue: string;
}

interface ConfigTableProps {
  rows: TableRow[];
}

export const ConfigTable: React.FC<ConfigTableProps> = ({ rows }) => {
  return (
    <div className="my-6 w-full overflow-x-auto">
      <table className="w-full border-collapse text-sm">
        <thead className="bg-[--color-table-header-bg]">
          <tr>
            <th className="border border-[--color-table-border] px-4 py-3 text-left font-bold text-[--color-secondary-foreground]">
              Variable
            </th>
            <th className="border border-[--color-table-border] px-4 py-3 text-left font-bold text-[--color-secondary-foreground]">
              Description
            </th>
            <th className="border border-[--color-table-border] px-4 py-3 text-left font-bold text-[--color-secondary-foreground]">
              Default
            </th>
          </tr>
        </thead>
        <tbody className="divide-y divide-[--color-table-border]">
          {rows.map((row, index) => (
            <tr
              key={index}
              className={
                index % 2 === 0 ? 'bg-[--color-table-row-even]' : 'bg-[--color-table-row-odd]'
              }
            >
              <td className="border border-[--color-table-border] px-4 py-3 font-mono text-[--color-primary]">
                {row.variable}
              </td>
              <td className="border border-[--color-table-border] px-4 py-3 text-[--color-text]">
                {row.description}
              </td>
              <td className="border border-[--color-table-border] px-4 py-3 font-mono text-[--color-text-light] dark:text-[--color-text-dark]">
                {row.defaultValue}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default ConfigTable;
